/**
 * Build Static Site for ServerByt
 * 
 * This script:
 * 1. Builds a static HTML export of the public website
 * 2. Excludes admin pages (they stay on Railway)
 * 3. Updates API calls to point to Railway
 * 4. Creates Apache-compatible .htaccess
 * 5. Outputs to /static-deploy folder
 * 
 * Usage: node scripts/build-static.js
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const OUT_DIR = path.join(ROOT_DIR, 'static-deploy');
const RAILWAY_API = process.env.RAILWAY_API_URL || 'https://quantalyze-api.up.railway.app';

console.log('🚀 Building Static Site for ServerByt...\n');

// Step 1: Clean output directory
console.log('1️⃣ Cleaning output directory...');
if (fs.existsSync(OUT_DIR)) {
  fs.rmSync(OUT_DIR, { recursive: true, force: true });
}
fs.mkdirSync(OUT_DIR, { recursive: true });

// Step 2: Backup original config and use static config
console.log('2️⃣ Preparing static build config...');
const originalConfig = path.join(ROOT_DIR, 'next.config.js');
const backupConfig = path.join(ROOT_DIR, 'next.config.backup.js');
const staticConfig = path.join(ROOT_DIR, 'next.config.static.js');

// Backup original
if (fs.existsSync(originalConfig)) {
  fs.copyFileSync(originalConfig, backupConfig);
}

// Use static config
fs.copyFileSync(staticConfig, originalConfig);

console.log('3️⃣ Building static export...');
try {
  execSync('npx next build', {
    cwd: ROOT_DIR,
    stdio: 'inherit',
    env: {
      ...process.env,
      RAILWAY_API_URL: RAILWAY_API,
      NEXT_PUBLIC_API_URL: RAILWAY_API,
    }
  });
} catch (error) {
  // Restore original config even on failure
  if (fs.existsSync(backupConfig)) {
    fs.copyFileSync(backupConfig, originalConfig);
    fs.unlinkSync(backupConfig);
  }
  console.error('❌ Build failed:', error.message);
  process.exit(1);
}

// Restore original config
if (fs.existsSync(backupConfig)) {
  fs.copyFileSync(backupConfig, originalConfig);
  fs.unlinkSync(backupConfig);
  console.log('   ✓ Restored original next.config.js');
}

// Step 4: Copy exported files
console.log('4️⃣ Copying static files...');
const nextOutDir = path.join(ROOT_DIR, 'out');
if (fs.existsSync(nextOutDir)) {
  copyRecursive(nextOutDir, OUT_DIR);
} else {
  console.error('❌ No output directory found. Make sure next.config.static.js has output: "export"');
  process.exit(1);
}

// Step 5: Remove admin pages from static build (keep on Railway only)
console.log('5️⃣ Removing admin pages (admin stays on Railway)...');
const adminDir = path.join(OUT_DIR, 'admin');
if (fs.existsSync(adminDir)) {
  fs.rmSync(adminDir, { recursive: true, force: true });
  console.log('   ✓ Removed /admin directory');
}

// Step 6: Create .htaccess for Apache
console.log('6️⃣ Creating .htaccess for Apache...');
const htaccess = `# Quantalyze Static Site - Apache Configuration
# Generated by build-static.js

# Enable RewriteEngine
RewriteEngine On

# Force HTTPS
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Remove www
RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]
RewriteRule ^(.*)$ https://%1/$1 [R=301,L]

# Redirect /admin/* to Railway
RewriteRule ^admin(.*)$ ${RAILWAY_API}/admin$1 [R=302,L]

# Redirect /api/* to Railway
RewriteRule ^api/(.*)$ ${RAILWAY_API}/api/$1 [P,L]

# Handle trailing slashes
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !(.*)/$
RewriteRule ^(.*)$ $1/ [L,R=301]

# Serve .html files without extension
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}.html -f
RewriteRule ^(.*)$ $1.html [L]

# Handle SPA fallback for any remaining routes
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.html [L]

# Enable compression
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/css application/json
  AddOutputFilterByType DEFLATE application/javascript text/javascript
  AddOutputFilterByType DEFLATE image/svg+xml
</IfModule>

# Cache static assets
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/jpg "access plus 1 month"
  ExpiresByType image/jpeg "access plus 1 month"
  ExpiresByType image/gif "access plus 1 month"
  ExpiresByType image/png "access plus 1 month"
  ExpiresByType image/webp "access plus 1 month"
  ExpiresByType image/svg+xml "access plus 1 month"
  ExpiresByType text/css "access plus 1 week"
  ExpiresByType application/javascript "access plus 1 week"
</IfModule>

# Security headers
<IfModule mod_headers.c>
  Header set X-Content-Type-Options "nosniff"
  Header set X-Frame-Options "SAMEORIGIN"
  Header set X-XSS-Protection "1; mode=block"
  Header set Referrer-Policy "strict-origin-when-cross-origin"
</IfModule>

# Error pages
ErrorDocument 404 /404.html
`;

fs.writeFileSync(path.join(OUT_DIR, '.htaccess'), htaccess);
console.log('   ✓ Created .htaccess');

// Step 7: Create deployment info file
console.log('7️⃣ Creating deployment info...');
const deployInfo = {
  generatedAt: new Date().toISOString(),
  railwayApi: RAILWAY_API,
  staticHost: 'https://quantalyze.co.in',
  instructions: [
    'Upload all contents of this folder to ServerByt public_html',
    'Make sure .htaccess is uploaded (hidden file)',
    'Admin panel is accessible at Railway URL',
    'API calls from static site go to Railway'
  ]
};
fs.writeFileSync(
  path.join(OUT_DIR, 'deploy-info.json'),
  JSON.stringify(deployInfo, null, 2)
);

console.log('\n✅ Static build complete!');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('📁 Output folder: static-deploy/');
console.log('🌐 Static site:   https://quantalyze.co.in');
console.log('🔧 Admin panel:   ' + RAILWAY_API + '/admin');
console.log('📡 API endpoint:  ' + RAILWAY_API + '/api');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('\n📤 Upload contents of static-deploy/ to ServerByt public_html');

// Helper: Copy directory recursively
function copyRecursive(src, dest) {
  const entries = fs.readdirSync(src, { withFileTypes: true });
  
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    
    if (entry.isDirectory()) {
      fs.mkdirSync(destPath, { recursive: true });
      copyRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}
